export const gifts = [
    {
        id: 0,
        name: "Кружка с вашим фото «Лучшей подруге»",
        giftImage: require('../../img/cup.jpg').default,
        price: "650 руб",
        section: "С вашим текстом",
    },
    {
        id: 1,
        name: "Кружка с вашим именем «С 8 марта»",
        giftImage: require('../../img/cup1.jpg').default,
        price: "650 руб",
        section: "С вашим текстом",
    },
    {
        id: 2,
        name: "Кружка с вашим именем «Хоть и не военный»",
        giftImage: require('../../img/cup2.jpg').default,
        price: "650 руб",
        section: "С вашим текстом",
    },
    {
        id: 3,
        name: "Набор «Самой лучшей»",
        giftImage: require('../../img/forher.jpeg').default,
        price: "1100 руб",
        section: "Для неё",
    },
    {
        id: 4,
        name: "Набор «Для него»",
        giftImage: require('../../img/forher.jpg').default,
        price: "1250 руб",
        section: "Для него",
    },
    {
        id: 5,
        name: "Новогодний набор «Для него»",
        giftImage: require('../../img/forhim.jpg').default,
        price: "650 руб",
        section: "Для него",
    },
    {
        id: 6,
        name: "Новогодний набор «Для неё»",
        giftImage: require('../../img/forhim1.jpg').default,
        price: "650 руб",
        section: "Для неё",
    },
    {
        id: 7,
        name: "Ремень «Самый родной и любимый»",
        giftImage: require('../../img/forhim2.jpg').default,
        price: "650 руб",
        section: "Для него",
    },
    {
        id: 8,
        name: "Мешочек «С днем Святого Валентина»",
        giftImage: require('../../img/pouch.jpg').default,
        price: "650 руб",
        section: "С вашим текстом",
    },
    {
        id: 9,
        name: "Мешочек «За хорошоие поступки от Деда Мороза»",
        giftImage: require('../../img/pouch1.jpg').default,
        price: "650 руб",
        section: "С вашим текстом",
    },
    {
        id: 10,
        name: "Мешочек «С днем Святого Валентина»",
        giftImage: require('../../img/pouch2.jpg').default,
        price: "650 руб",
        section: "С вашим текстом",
    },
    {
        id: 11,
        name: "Набор «Love»",
        giftImage: require('../../img/forher1.jpeg').default,
        price: "650 руб",
        section: "Для неё",
    },
];