export const gifts = [
  {
    id: 0,
    name: "Кружка с вашим фото «Лучшей подруге»",
    giftImage: require("../src/img/cup.jpg").default,
    price: 333,
    section: "С вашим текстом",
  },
  {
    id: 1,
    name: "Кружка с вашим именем «С 8 марта»",
    giftImage: require("../src/img/cup1.jpg").default,
    price: 345,
    section: "С вашим текстом",
  },
  {
    id: 2,
    name: "Кружка с вашим именем «Хоть и не военный»",
    giftImage: require("../src/img/cup2.jpg").default,
    price: 764,
    section: "С вашим текстом",
  },
  {
    id: 3,
    name: "Набор «Самой лучшей»",
    giftImage: require("../src/img/forher.jpeg").default,
    price: "1144",
    section: "Для неё",
  },
  {
    id: 4,
    name: "Набор «Для него»",
    giftImage: require("../src/img/forher.jpg").default,
    price: 1353,
    section: "Для него",
  },
  {
    id: 5,
    name: "Новогодний набор «Для него»",
    giftImage: require("../src/img/forhim.jpg").default,
    price: 2452,
    section: "Для него",
  },
  {
    id: 6,
    name: "Новогодний набор «Для неё»",
    giftImage: require("../src/img/forhim1.jpg").default,
    price: 1234,
    section: "Для неё",
  },
  {
    id: 7,
    name: "Ремень «Самый родной и любимый»",
    giftImage: require("../src/img/forhim2.jpg").default,
    price: 4212,
    section: "Для него",
  },
  {
    id: 8,
    name: "Мешочек «С днем Святого Валентина»",
    giftImage: require("../src/img/pouch.jpg").default,
    price: 1234,
    section: "С вашим текстом",
  },
  {
    id: 9,
    name: "Мешочек «За хорошоие поступки от Деда Мороза»",
    giftImage: require("../src/img/pouch1.jpg").default,
    price: 532,
    section: "С вашим текстом",
  },
  {
    id: 10,
    name: "Мешочек «С днем Святого Валентина»",
    giftImage: require("../src/img/pouch2.jpg").default,
    price: 322,
    section: "С вашим текстом",
  },
  {
    id: 11,
    name: "Набор «Love»",
    giftImage: require("../src/img/forher1.jpeg").default,
    price: 1345,
    section: "Для неё",
  },
];
